### ISSUE TITLE
add-my-email function does not detect username at beginning of line

### ISSUE THREAD

**Issue by schae234** [UMN-EGGL/MSI-Setup#10]
Add a check in the [grep command](https://github.com/UMNPonyClub/MSI-Setup/blob/ae1e0c8fc0d0f1ec0ca8772c52865c1139faf4fc/mccuem_profile#L52) to check that the username is at the beginning of the line.

This for instance would say that I had an email address when I do not because my username would be recognize:
```
mccuem    schae234@umn.edu
```
Also add a helpful error message when the email cannot be found. Right now I see:

```
schae234@labqi048 [~/Documents] % freeze EMS_WebPage_Survey_Backups
[qsub: illegal -M value]

usage: qsub [-a date_time] [-A account_string] [-b secs]
    [-c [ none | { enabled | periodic | shutdown |
    depth=<int> | dir=<path> | interval=<minutes>}... ]
    [-C directive_prefix] [-d path] [-D path]
    [-e path] [-h] [-I] [-j oe|eo|n] [-k {oe}] [-K <kill delay seconds>] 
    [-l resource_list] [-m n|{abe}] [-M user_list] [-N jobname] [-o path] 
    [-p priority] [-P proxy_user [-J <jobid]] [-q queue] [-r y|n] 
    [-S path] [-t number_to_submit] [-T type]  [-u user_list] [-w] path
    [-W additional_attributes] [-v variable_list] [-V ] [-x] [-X] [-z] [script]
```

Becuase the script [gets to](https://github.com/UMNPonyClub/MSI-Setup/blob/ae1e0c8fc0d0f1ec0ca8772c52865c1139faf4fc/mccuem_profile#L81) with an incorrect email.

**Comment by jackstanek** [comment]
The function should be detecting the email at the beginning of the line now.
